### ISSUE TITLE
Add Permissions

### ISSUE THREAD

**Issue by yhsanave** [sjavi4/PlayerDoll#10]
Add permissions support or at least make all commands OP until permissions are implemented.

**Comment by sjavi4** [comment]
Basically all commands are usable for only one who has permission. (Except doll create / dolllist / dollhelp)
Non-OP are not able to use commands to control dolls if they are not gset/pset.
if you want to disable normal players from creating doll, you can set `MaxDollPerPlayer` to 0 in config, OP will bypass that limit.
Or you are talking other commands that are not included.
(Permission config is working in progress)

**Comment by sjavi4** [comment]
New Permission System has added from 1.17 (current [1.18](https://modrinth.com/plugin/playerdoll/versions))
hope it meets your wants.
