### ISSUE TITLE
Set doll custom skin with gameprofile uuid

### ISSUE THREAD

**Issue by shou692199** [sjavi4/PlayerDoll#102]
**Is your feature request related to a problem? Please describe.**
When creating a new doll, we can only choose from server player list.

**Describe the solution you'd like**
Add support for players to set custom skin with gameprofile uuid.

**Describe alternatives you've considered**
It would be great if player can also enter url to download skin image file.

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll/commit/b3953ad9eae8fca0bc525dc394d553d0331c82c1
