### ISSUE TITLE
Auto replenishment feature

### ISSUE THREAD

**Issue by shou692199** [sjavi4/PlayerDoll#106]
Replenish items held in main hand or off hand automatically.

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll/issues/69

Doll are just player, so majority of player-related plugins could fulfill the needs.

Or i might provide an extra addon when there is no similar feature that is available currently.

**Comment by sjavi4** [comment]
Actually i didn't know would Doll trigger those event or not, since it is not completely follow the vanilla code to run.
Perhaps it works.
Please let me know if the plugin works or not.

**Comment by shou692199** [comment]
It doesn't work.

**Comment by sjavi4** [comment]
I will work it out

**Comment by shou692199** [comment]
Is there anything related to `convert-player: true`.
Seems like it doesn't trigger onBlockPlace event.
```@EventHandler
    fun onBlockPlace(event: BlockPlaceEvent) {
        val player = event.player
        Bukkit.getLogger().info("${player.name} ${Settings.GAMEMODES} ${player.hasPermission(Settings.USE_PERMISSION)}")
        if(Settings.GAMEMODES.contains(player.gameMode) && player.hasPermission(Settings.USE_PERMISSION)){
            val swapItem = player.inventory.itemInMainHand.clone()
            scheduleAdapter.scheduleDelayedTask(Runnable { swap(swapItem, player) }, 1L, player)
        }
    }
```
![image](https://github.com/user-attachments/assets/666f8074-30f1-4621-a8b8-6f7106515ded)

**Comment by shou692199** [comment]
Seems like it's caused by permission issue though the doll has op role.

**Comment by sjavi4** [comment]
> Is there anything related to `convert-player: true`. Seems like it doesn't trigger onBlockPlace event.

`convert-player` is a feature to support real players to perform actions like Dolls, using the identifier "_" as self.

> Seems like it doesn't trigger onBlockPlace event.

BlockPlaceEvent should only trigger if player places block, for other consumption, maybe [PlayerItemConsumeEvent](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/player/PlayerItemConsumeEvent.html)

**Comment by sjavi4** [comment]
> It doesn't work. Tried [BestTools](https://www.spigotmc.org/resources/besttools.81490/) and [BlockSwapper](https://modrinth.com/plugin/blockswapper/version/1.2.0).

Besttools Can trigger replenishing by promoting the Doll to OP, maybe there is other some permission related settings have to do with.

**Comment by shou692199** [comment]
Player permissions are managed by LuckPerms, but PlayerDoll is causing SQL error. This can be a reason.
```
[14:33:16] [Thread-204/ERROR]: [LuckPerms] Exception occurred whilst loading data for fdc889cc-595c-4d1f-b157-3f5ebaab8e02 - -firework
java.util.concurrent.CompletionException: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_F ON PUBLIC.LUCKPERMS_PLAYERS(UUID) VALUES ( /* 273 */ 'fdc889cc-595c-4d1f-b157-3f5ebaab8e02' )"; SQL statement:
INSERT INTO `luckperms_players` (uuid, username, primary_group) VALUES(?, ?, ?) [23505-214]
	at me.lucko.luckperms.common.util.AsyncInterface.lambda$future$0(AsyncInterface.java:53) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_F ON PUBLIC.LUCKPERMS_PLAYERS(UUID) VALUES ( /* 273 */ 'fdc889cc-595c-4d1f-b157-3f5ebaab8e02' )"; SQL statement:
INSERT INTO `luckperms_players` (uuid, username, primary_group) VALUES(?, ?, ?) [23505-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:508) ~[?:?]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[?:?]
	at org.h2.message.DbException.get(DbException.java:223) ~[?:?]
	at org.h2.message.DbException.get(DbException.java:199) ~[?:?]
	at org.h2.index.Index.getDuplicateKeyException(Index.java:525) ~[?:?]
	at org.h2.mvstore.db.MVSecondaryIndex.checkUnique(MVSecondaryIndex.java:223) ~[?:?]
	at org.h2.mvstore.db.MVSecondaryIndex.add(MVSecondaryIndex.java:184) ~[?:?]
	at org.h2.mvstore.db.MVTable.addRow(MVTable.java:519) ~[?:?]
	at org.h2.command.dml.Insert.insertRows(Insert.java:174) ~[?:?]
	at org.h2.command.dml.Insert.update(Insert.java:135) ~[?:?]
	at org.h2.command.dml.DataChangeStatement.update(DataChangeStatement.java:74) ~[?:?]
	at org.h2.command.CommandContainer.update(CommandContainer.java:169) ~[?:?]
	at org.h2.command.Command.executeUpdate(Command.java:252) ~[?:?]
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:254) ~[?:?]
	at me.lucko.luckperms.common.storage.implementation.sql.SqlStorage.savePlayerData(SqlStorage.java:687) ~[?:?]
	at me.lucko.luckperms.common.storage.Storage.lambda$savePlayerData$20(Storage.java:242) ~[?:?]
	at me.lucko.luckperms.common.util.AsyncInterface.lambda$future$0(AsyncInterface.java:48) ~[?:?]
	... 7 more
```

**Comment by sjavi4** [comment]
After some testing, the permission works fine for Doll now, the permission for replenishment works too.

https://github.com/sjavi4/PlayerDoll/commit/5732fb0c9eab92e09d229197d8d37d27f103b3b8
https://github.com/sjavi4/PlayerDoll/commit/2aeff10e68de499bca78c75d913fc0ebe211db48
https://github.com/sjavi4/PlayerDoll/commit/d6fe74debe7c0b5b7b5cf13f976a0b89e34a812d

Here is the test release. https://github.com/sjavi4/PlayerDoll/releases/tag/v2.2.1

The test release included the update from v2.2


Please check and see the other problems are solved or not.

**Comment by shou692199** [comment]
Connection timed out after updating from 2.1 to this release

**Comment by sjavi4** [comment]
Got the problem, i have some missing code for other versions.
I will give the release again.

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll/releases/tag/v2.2.2

**Comment by sjavi4** [comment]
> ```
> [14:33:16] [Thread-204/ERROR]: [LuckPerms] Exception occurred whilst loading data for fdc889cc-595c-4d1f-b157-3f5ebaab8e02 - -firework
> java.util.concurrent.CompletionException: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.PRIMARY_KEY_F ON PUBLIC.LUCKPERMS_PLAYERS(UUID) VALUES ( /* 273 */ 'fdc889cc-595c-4d1f-b157-3f5ebaab8e02' )"; SQL statement:
> INSERT INTO `luckperms_players` (uuid, username, primary_group) VALUES(?, ?, ?) [23505-214]
> ```

> 
> Similar error in DiscordSRV
> 
> ```
> [16:33:22 ERROR]: [DiscordSRV] java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'fdc889cc-595c-4d1f-b157-3f5ebaab8e02' for
>  key 'codes_uuid_uindex'
> [16:33:22 ERROR]: [DiscordSRV]  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:109)
> [16:33:22 ERROR]: [DiscordSRV]  at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:114)
> [16:33:22 ERROR]: [DiscordSRV]  at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:988)
> [16:33:22 ERROR]: [DiscordSRV]  at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1166)
> [16:33:22 ERROR]: [DiscordSRV]  at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1101)
> [16:33:22 ERROR]: [DiscordSRV]  at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1467)
> [16:33:22 ERROR]: [DiscordSRV]  at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1084)
> [16:33:22 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.29.0.jar//github.scarsz.discordsrv.objects.managers.link.JdbcAccountLinkManager.genera
> teCode(JdbcAccountLinkManager.java:339)
> [16:33:22 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.29.0.jar//github.scarsz.discordsrv.modules.requirelink.RequireLinkModule.check(Require
> LinkModule.java:107)
> [16:33:22 ERROR]: [DiscordSRV]  at DiscordSRV-Build-1.29.0.jar//github.scarsz.discordsrv.modules.requirelink.RequireLinkModule.onEventNormal
> (RequireLinkModule.java:288)
> [16:33:22 ERROR]: [DiscordSRV]  at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor212.execute(Unknown Source)
> [16:33:22 ERROR]: [DiscordSRV]  at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
> [16:33:22 ERROR]: [DiscordSRV]  at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
> [16:33:22 ERROR]: [DiscordSRV]  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
> [16:33:22 ERROR]: [DiscordSRV]  at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
> [16:33:22 ERROR]: [DiscordSRV]  at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131)
> [16:33:22 ERROR]: [DiscordSRV]  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628)
> [16:33:22 ERROR]: [DiscordSRV]  at me.autobot.addonDoll.connection.DollLoginListener.lambda$callPreLogin$2(DollLoginListener.java:51)
> [16:33:22 ERROR]: [DiscordSRV]  at java.base/java.lang.Thread.run(Thread.java:1583)
> ```

I think this problem is duplicated UUID entry appeared in your database.
Maybe you can have a look inside the database and clean up the duplicated one.

**Comment by shou692199** [comment]
Now the doll is being spawned at where it logout instead of player location.
Also, doll use command is not working.

**Comment by sjavi4** [comment]
I made the Doll not having OP permission now, which Doll will now respect other plugins. https://github.com/sjavi4/PlayerDoll/commit/f9d227109d76e13b856ba5df129941b5d52a9804

Make sure you have given the corrisponding permissions, or find a random place (other than spawn, nor other protected area) to test the actions.

**Comment by shou692199** [comment]
Still can't get doll working inside residence, even teleporting and using bed.

**Comment by shou692199** [comment]
After that, I found a way to auto replenish in v2.1, thank you for making such a great plugin.
