### ISSUE TITLE
attack command syntax not clear

### ISSUE THREAD

**Issue by EmilieSong** [sjavi4/PlayerDoll#11]
wont attack armor stand no idea why, please include command syntax and example in the help menu

**Comment by sjavi4** [comment]
Please ensure the Doll and the target are outside of Spawn Protection area (ie origin spawn of world with certain distance)

**In general**
- Attack continuous is for mining blocks
- Attack interval <interval> <offset> is for periodic attack (mainly for entities)

**Comment by sjavi4** [comment]
A remade version of Tab suggestion System has updated at [1.17](https://modrinth.com/plugin/playerdoll/version/1.17).
Also help command has detailised, hope this help.
Please have a look.
