### ISSUE TITLE
Trying to find a way to thank you for this plugin

### ISSUE THREAD

**Issue by Primeltoaster** [sjavi4/PlayerDoll#12]
I hope it's not annoying that I'm posting this in the "issues" section, but I couldn't find another way of contacting you about this plugin. I wanted to say that this little plugin is huuuugely appreciated by my friends and me; we've been looking for something simple to help us keep our farms working; we spent a LOT of time but couldn't find a solution. I'm so happy I stumbled across your plugin one day and I hope you can continue updating it! Cheers :)

**Comment by sjavi4** [comment]
Thank you for the appreciation. This is glad to see someone who likes this plugin.
However, this plugin is still on the developing stage, and i am sorry about the rapid changes and inconvience in the plugin.
Hope to bring you all a better, stabler plugin soon! <3
