### ISSUE TITLE
interferes with four forcepack plugin

### ISSUE THREAD

**Issue by blue-pinapple** [sjavi4/PlayerDoll#15]
Force pack forces players to use resource packs. It kicks then if they don't accept it. It obviously thinks that the dolls are players https://modrinth.com/plugin/forcepack
I just disabled it for now, but it would be nice if you can fix it

**Comment by sjavi4** [comment]
Force Pack's dependency code for handling Fake Players (https://github.com/SamB440/packetevents/commit/75af221f779fd26f11880cf554ae4937e721201e).
I made a support for this by warpping a `EmbeddedChannel` class by `FakeChannel` class.
Kick has prevented by passing the Fake player check.

Meanwhile, the `Force Pack` plugin did not handle well on Null check.
```
java.lang.NullPointerException: Cannot invoke "com.convallyria.forcepack.spigot.libs.pe-api.protocol.player.User.getClientVersion()" because the return value of "com.convallyria.forcepack.spigot.libs.pe-api.manager.player.PlayerManager.getUser(Object)" is null
```
It will pop up error alert in console when Spawning Doll but not affecting the Server.

You may write an issue to the author of the plugin to provide some suggestion about handling Fake players.
(ie. Fake player Connection check, Null check)

Please see v1.20.2 on Modrinth [Download](https://modrinth.com/plugin/playerdoll/versions)

**Comment by SamB440** [comment]
An NPC plugin should not be calling join events. ViaVersion spams warnings because of this as well. How am I, and why should I, have to determine if a plugin is an NPC in `PlayerJoinEvent`?

**Comment by sjavi4** [comment]
I am sorry for the inconvience cause from this plugin. This is my responsibility to make this plugin to enhance compatibility.
That suggestion was just a reminder, not an order.
Here is a newer version of PlayerDoll that will not trigger `PlayerJoinEvent` by other plugins when Spawning NPC.
Please have a look. Thank you.
https://modrinth.com/plugin/playerdoll/version/1.20.3

**Comment by SamB440** [comment]
I don't have an issue with your plugin specifically. I just think a lot of NPC plugins are flawed in their use of NMS - this includes Citizens, which forced me to check `PlayerTeleportEvent` and `PlayerMoveEvent` on another plugin, because for some reason they call that event for NPCs.

I checked what I did there so I guess this is the solution if not calling a bukkit event isn't possible:
```
final boolean isNpcPlayer = Bukkit.getPlayer(player.getUniqueId()) == null;
```

**Comment by SamB440** [comment]
The new version does indeed fix the problem, however ViaVersion still warns:
`[12:35:19 WARN]: [ViaVersion] Could not find UserConnection for logging-in player 3691982f-ed1e-3721-b604-dadfefc109f0`

**Comment by sjavi4** [comment]
After some testing and research.
It is the problem of Event priority and Plugin loading order, i tried to make my plugin load earlier than ViaVersion. https://github.com/sjavi4/PlayerDoll/commit/7bd664354f4e1a64bb2c3eeea4ab78f88b2517d7

It should be fine until some plugins are having a higher load order which make their plugin event execute first.
