### ISSUE TITLE
Server crash on spigot server with ProtocolLib plugin

### ISSUE THREAD

**Issue by L-the-forgettable** [sjavi4/PlayerDoll#16]
Steps to reproduce: 
1. Create new doll
2. attempt to spawn doll while ProtocolLib plugin is installed

Expected result: Player Doll is spawned without a hitch
Actual result: Server crashes

Crash report: 
[latest_crash_report.txt](https://github.com/sjavi4/PlayerDoll/files/13997300/latest_crash_report.txt)

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll/commit/91f7241424203b5b7341425729aca3f28e683a69

Please check v1.21(https://modrinth.com/plugin/playerdoll/version/1.21) to see if the problem has fixed or not.

**Comment by L-the-forgettable** [comment]
This appears to have been fixed
