### ISSUE TITLE
Permissions (Feature request)

### ISSUE THREAD

**Issue by L-the-forgettable** [sjavi4/PlayerDoll#18]
Would it be possible to get a standard permissions integration for use in plugins like Luckperms?
The current system is a little clunky, and non-intuitive so introducing that kind of integration would be very useful

**Comment by sjavi4** [comment]
Would you like to explain a bit about how to use with Luckperms? (I haven't host a server or touch permission before)
Is it like me providing some permission nodes for server owner to set for their permission groups, then I use LuckPerms' API to get player has permission or not.
So I have to do is to set a default list of permission, leaving the rest for server owner to figure it out?

**Comment by L-the-forgettable** [comment]
I don't develop plugins myself, however doing a little searching reveals that you aren't directly working with the permissions plugin itself, you're actually working with the server by giving it what commands need which permissions, and the server in turn works with the permissions plugin to figure out how to handle the rest. You can read up a little bit more on this [here](https://mineacademy.org/tutorial-5), with an example being directly in the webpage, and [here](https://github.com/GriefPrevention/GriefPrevention/blob/master/src/main/resources/plugin.yml).

Please keep in mind that I myself have never designed a plugin before, so take what I've written with a grain of salt
