### ISSUE TITLE
Can the doll automatically obtain genuine skin or manually set the skin

### ISSUE THREAD

**Issue by herobrinein** [sjavi4/PlayerDoll#2]

**Comment by sjavi4** [comment]
You can set the skin by following a player ID after spawn command
eg /doll sth spawn [Player id you want]

**Comment by sjavi4** [comment]
Skin data will be saved in doll.yml in upcoming version (v1.3)

**Comment by herobrinein** [comment]
sure

**Comment by herobrinein** [comment]
Perhaps third-party skins can be used through some skin plugins? For example, directly using links

**Comment by sjavi4** [comment]
Updated

**Comment by sjavi4** [comment]
Unfortunately, it seems there is no way to manually change the skin that is not exist from player profile.
The code of fetching skin as doll profile:
1. Get UUID of player Name from https://api.mojang.com/users/profiles/minecraft/[SkinName]
2. Get player Profile from https://sessionserver.mojang.com/session/minecraft/profile/[UUID]?unsigned=false
3. Store the Signature
4. Decode base64 "value" then store them into yaml

Which of these procedures can be done by filling skinName in doll spawn command.

Maybe someday i will remake/implement skin function 😢
