### ISSUE TITLE
Plug-in compatibility issues error

### ISSUE THREAD

**Issue by xiaoluofa** [sjavi4/PlayerDoll#22]
It is not compatible with the synchronization plug-in, and the dummy cannot pick up items or be harmed. The synchronization plug-in used is https://github.com/jianjianai/KnapsackToGo4 。
I didn't test other synchronization plug-ins.
There is no error log for this error

**Comment by sjavi4** [comment]
This is a bit complicated
Or you can just spawn another Doll to deal with this problem?
Otherwise, it would be a huge modification of code. 
(like putting all Doll playerdata into config, and it is not 100% prevent duping when multi doll spawn in different server)
And the plugin cannot do cross-server communitcation, which it is hard to handle the same Doll in many servers.

**Comment by sjavi4** [comment]
If the doll inventory and ender chest has duping issue across servers, i might be able to do some support with this.

**Comment by sjavi4** [comment]
> It is not compatible with the synchronization plug-in, and the dummy cannot pick up items or be harmed. The synchronization plug-in used is https://github.com/jianjianai/KnapsackToGo4 。 I didn't test other synchronization plug-ins. There is no error log for this error

Could you tell me what is the goal to make Doll work across servers, the problem is a bit vague.

**Comment by xiaoluofa** [comment]
> > It is not compatible with the synchronization plug-in, and the dummy cannot pick up items or be harmed. The synchronization plug-in used is https://github.com/jianjianai/KnapsackToGo4 。 I didn't test other synchronization plug-ins. There is no error log for this error
> 
> Could you tell me what is the goal to make Doll work across servers, the problem is a bit vague.

I don't need to synchronize any data from dummies, as you know, there are very few folia-compatible plug-ins. I used BC to allow my players to experience other plug-ins on specific servers. The synchronization plug-in depends on preventing the dummy from getting the item. I think you can add a command to let the player put the item directly into the dummy's backpack. So you don't have to modify a lot of code.

**Comment by sjavi4** [comment]
> > > It is not compatible with the synchronization plug-in, and the dummy cannot pick up items or be harmed. The synchronization plug-in used is https://github.com/jianjianai/KnapsackToGo4 。 I didn't test other synchronization plug-ins. There is no error log for this error
> > 
> > 
> > Could you tell me what is the goal to make Doll work across servers, the problem is a bit vague.
> 
> I don't need to synchronize any data from dummies, as you know, there are very few folia-compatible plug-ins. I used BC to allow my players to experience other plug-ins on specific servers. The synchronization plug-in depends on preventing the dummy from getting the item. I think you can add a command to let the player put the item directly into the dummy's backpack. So you don't have to modify a lot of code.

As the demonstration from the synchronize plugin, a locked player will not be able to update their data until the prior player left. Which i think even if player can set items into their inventory, this will not be able to update into player data.

**Comment by xiaoluofa** [comment]
> > > > It is not compatible with the synchronization plug-in, and the dummy cannot pick up items or be harmed. The synchronization plug-in used is https://github.com/jianjianai/KnapsackToGo4 。 I didn't test other synchronization plug-ins. There is no error log for this error
> > > 
> > > 
> > > Could you tell me what is the goal to make Doll work across servers, the problem is a bit vague.
> > 
> > 
> > I don't need to synchronize any data from dummies, as you know, there are very few folia-compatible plug-ins. I used BC to allow my players to experience other plug-ins on specific servers. The synchronization plug-in depends on preventing the dummy from getting the item. I think you can add a command to let the player put the item directly into the dummy's backpack. So you don't have to modify a lot of code.
> 
> As the demonstration from the synchronize plugin, a locked player will not be able to update their data until the prior player left. Which i think even if player can set items into their inventory, this will not be able to update into player data.

I searched the database of the synchronization plug-in, and there was no UUID for dummies. Even before I used the synchronization plug-in, I gave the dummy item, I rewrote and summoned this dummy item to display, but could not pick it up and throw it out again.
![image](https://github.com/sjavi4/PlayerDoll/assets/75927411/df2e2803-c1c5-4d12-9c79-9af9234918f5)
Although items are not available, previous items can work properly, such as attack

**Comment by xiaoluofa** [comment]
I think we can give it a try, give the dummy items directly, and add an instruction to make the dummy throw out all the items in the backpack. This may be easier than rewriting. But I'm not sure if there will be a problem with other synchronization plug-ins.

**Comment by sjavi4** [comment]
> I searched the database of the synchronization plug-in, and there was no UUID for dummies. Even before I used the synchronization plug-in, I gave the dummy item, I rewrote and summoned this dummy item to display, but could not pick it up and throw it out again.
Although items are not available, previous items can work properly, such as attack

so the Doll did not ever exist on other server at the same time?
the first spawn is already being locked by the plugin?

**Comment by xiaoluofa** [comment]
> > I searched the database of the synchronization plug-in, and there was no UUID for dummies. Even before I used the synchronization plug-in, I gave the dummy item, I rewrote and summoned this dummy item to display, but could not pick it up and throw it out again.
> > Although items are not available, previous items can work properly, such as attack
> 
> so the Doll did not ever exist on other server at the same time? the first spawn is already being locked by the plugin?

Yes, doll exists only in folia server.

**Comment by xiaoluofa** [comment]
> > I searched the database of the synchronization plug-in, and there was no UUID for dummies. Even before I used the synchronization plug-in, I gave the dummy item, I rewrote and summoned this dummy item to display, but could not pick it up and throw it out again.
> > Although items are not available, previous items can work properly, such as attack
> 
> so the Doll did not ever exist on other server at the same time? the first spawn is already being locked by the plugin?

I asked the author of the synchronization plug-in, which locked the dummy. So dummies can't be picked up or hurt.

**Comment by xiaoluofa** [comment]
The synchronization plug-in told me that I could try to add a player to join the event so that the synchronization plug-in could monitor and work properly. But it seems to conflict with the reset of the tree-cutting plug-in and check-in plug-in that I mentioned a few days ago.

**Comment by jianjianai** [comment]
Sorry, my English is not good

这个问题产生的原因是，在生成假人新的假人时没有发生“PlayerJoinEvent”事件，KnapsackToGo4会阻止玩家在完成数据同步之前的所有事件，因为没有发生“PlayerJoinEvent”事件，KnapsackToGo4就不会进行数据同步，也就一直处于同步未完成状态。

**Comment by sjavi4** [comment]
Letting PlayerJoinEvent enable for doll did solve the problem.

i am now working on Enabling PlayerJoinEvent for dolls, this might take some time to make sure most plugins that use this event go well.

**Comment by xiaoluofa** [comment]
> bad news, my pc was broken, i have no ways to test and finish the fix for a while. It is welcomed for reporting any issues when founded.

That's sad news. I'm looking forward to your repair.

**Comment by xiaoluofa** [comment]
期待新的进展

**Comment by sjavi4** [comment]
> 期待新的进展

Do [v1.25](https://modrinth.com/plugin/playerdoll/version/1.25) fixed your problem? Please have a look

**Comment by xiaoluofa** [comment]
> > 期待新的进展
> 
> Do [v1.25](https://modrinth.com/plugin/playerdoll/version/1.25) solved your problem? Please have a look

![image](https://github.com/sjavi4/PlayerDoll/assets/75927411/20af0837-7248-4ef8-b0c2-d3cdbd96b04a)
cant work

**Comment by xiaoluofa** [comment]
![image](https://github.com/sjavi4/PlayerDoll/assets/75927411/39b547ed-394b-4d8a-be37-a9d529c396ea)
![image](https://github.com/sjavi4/PlayerDoll/assets/75927411/b3eaa729-53dc-40b8-be21-e18f26a8cae6)

**Comment by sjavi4** [comment]
did the doll has it's config?

**Comment by xiaoluofa** [comment]
> did the doll has it's config (a latest version of Doll config) ?

I deleted the old configuration file of the plug-in, loaded the plug-in, created the dummy, and the configuration of the dummy appeared in the file.
![image](https://github.com/sjavi4/PlayerDoll/assets/75927411/840e53e6-f03e-4201-bd8b-230649094229)
I tried spawn to summon the dummy, but failed, and the server was automatically shut down.

**Comment by sjavi4** [comment]
> > did the doll has it's config (a latest version of Doll config) ?
> 
> I deleted the old configuration file of the plug-in, loaded the plug-in, created the dummy, and the configuration of the dummy appeared in the file. ![image](https://private-user-images.githubusercontent.com/75927411/310939052-840e53e6-f03e-4201-bd8b-230649094229.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4MjYzNzcsIm5iZiI6MTcwOTgyNjA3NywicGF0aCI6Ii83NTkyNzQxMS8zMTA5MzkwNTItODQwZTUzZTYtZjAzZS00MjAxLWJkOGItMjMwNjQ5MDk0MjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDE1NDExN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyYTgxMTc4NzUxNzNlYTg3Mzk1MjYyYjU3MDYwMGUyYzI5OTk4ZjgwNDI2OGM0ZmQ1MzA3NWYxZDk3N2RiYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RBbvl2-iHHh5PV333pkY5rHa1YNFMvdrz5j5dlJtpzM) I tried spawn to summon the dummy, but failed, and the server was automatically shut down.

Any crash log?

**Comment by sjavi4** [comment]
is the problem solved?

**Comment by xiaoluofa** [comment]
> is the problem solved?
I tested it on my test suit, and there's no problem this time. I'll try the formal environment tomorrow. I really failed last time.
