### ISSUE TITLE
JavaPlugin#getLogger

### ISSUE THREAD

**Issue by Beastion01** [sjavi4/PlayerDoll#23]
Hey sjavi4,

many thanks for your work, its a great feature!

I have installed your plugin and get an WARN in the log.

Log entry:
**[13:04:56 WARN]: Nag author(s): '[]' of 'PlayerDoll v1.24' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).**

i cant handle this, can you help me out here?

**Comment by sjavi4** [comment]
All System.out has been replaced by Logger.
Please see [v1.25](https://modrinth.com/plugin/playerdoll/version/1.25)
