### ISSUE TITLE
How to help the doll login in

### ISSUE THREAD

**Issue by Duan-7z** [sjavi4/PlayerDoll#26]
Well, maybe this is basic, but I still want to seek for help. 
My game version is 1.20.4, purpur server, using your latest plugin. (it doesn't really matter)
I managed to spawn a doll successfully. However, as the result of a login plugin (catseedlogin), the doll has to pass the login check, or it will be kicked from the server. Then I set the timeout kick to false and set password for the doll, but I barely find relative commands or config files to help me solve this, to make the doll login in.
So I'm wondering that is there a way I can issue commands as the identity of the doll? or there is a setting for the doll just passing through the login check?
 
There is another small problem by the way. My server has a whitelist. In order to spawn a doll, I have to turn off the whitelist. When the doll joins in, I'm going to turn on the whitelist again.

**Comment by sjavi4** [comment]
If there is a Bypass-Login permission from the login plugin,
you could try to apply the permission to `config.yml : doll-permission:`.
Or i will add function which allow Doll to execute some commands after they join the server.

**Comment by sjavi4** [comment]
by the way, all dolls are using the same ip as the server host, which i don't sure will it be blocked by ip restriction.

**Comment by Duan-7z** [comment]
> If there is a Bypass-Login permission from the login plugin, you could try to apply the permission to `config.yml : doll-permission:`. Or i will add function which allow Doll to execute some commands after they join the server.

Thanks for instant response, I'll keep trying to figure it out.
Besides, I truly appreciate it for your hard work developing a useful plugin.

**Comment by Duan-7z** [comment]
> by the way, all dolls are using the same ip as the server host (127.0.0.1), which i don't sure will they be blocked by ip restriction.

Got it.

**Comment by sjavi4** [comment]
[v1.25.2](https://modrinth.com/plugin/playerdoll/version/HoRbQccV) has released.
The noted problem should being solved.
Please have a look

**Comment by Duan-7z** [comment]
> > One more thing I want to ensure what to do in this config file specifically if I want the doll to chat with command when it join. ![image](https://private-user-images.githubusercontent.com/104820910/311977727-febd4ba4-580b-4ec1-b6b1-528bcf3c8880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMzA5MDAsIm5iZiI6MTcxMDIzMDYwMCwicGF0aCI6Ii8xMDQ4MjA5MTAvMzExOTc3NzI3LWZlYmQ0YmE0LTU4MGItNGVjMS1iNmIxLTUyOGJjZjNjODg4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwODAzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDZmNTU3ZGFlN2U2MmM3ZDRiY2FjNjFlYzJmNWJlNDY5MGUzMTU1MTY3NGRhZTM2ZTk2NGYzMDU3NjJiZWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oev-dNa64FAT_nnb5olYBdHazSr7EVDvg00naSm4z2A)
> 
> https://github.com/sjavi4/PlayerDoll/releases/tag/test I tried to change the connection flow to enhance stability.
> 
> For the chat-when-join key. You can write anything as a list of String. ie.
> 
> ```
> chat-when-join:
> - "the first message" # Send message "the first message" to chat
> - "Hi everyone, i'm %name% with UUID %uuid%" # broadcast Doll's name and Doll's UUID to chat.
> - "/help" # send help command
> ```
> 
> Each message will be delayed by chat-when-join-interval

Alright, I got that now, thanks for your help.

**Comment by Duan-7z** [comment]
> > One more thing I want to ensure what to do in this config file specifically if I want the doll to chat with command when it join. ![image](https://private-user-images.githubusercontent.com/104820910/311977727-febd4ba4-580b-4ec1-b6b1-528bcf3c8880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMzA5MDAsIm5iZiI6MTcxMDIzMDYwMCwicGF0aCI6Ii8xMDQ4MjA5MTAvMzExOTc3NzI3LWZlYmQ0YmE0LTU4MGItNGVjMS1iNmIxLTUyOGJjZjNjODg4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQwODAzMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDZmNTU3ZGFlN2U2MmM3ZDRiY2FjNjFlYzJmNWJlNDY5MGUzMTU1MTY3NGRhZTM2ZTk2NGYzMDU3NjJiZWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oev-dNa64FAT_nnb5olYBdHazSr7EVDvg00naSm4z2A)
> 
> https://github.com/sjavi4/PlayerDoll/releases/tag/test I tried to change the connection flow to enhance stability.
> 
> For the chat-when-join key. You can write anything as a list of String. ie.
> 
> ```
> chat-when-join:
> - "the first message" # Send message "the first message" to chat
> - "Hi everyone, i'm %name% with UUID %uuid%" # broadcast Doll's name and Doll's UUID to chat.
> - "/help" # send help command
> ```
> 
> Each message will be delayed by chat-when-join-interval

YES, everything works fine with this version of plugin now. Thank you again for your patience and work. This ISSUE could be closed as finished now, I think.

**Comment by Duan-7z** [comment]
![image](https://github.com/sjavi4/PlayerDoll/assets/104820910/74c82b6f-75e9-4b21-8c16-b95c9016c3f8)
um I have to let you notice this. 
The chat function doesn't work actually. Whenever I reload the server, the config file will be replaced. No matter what I do, the plugin will load the default config.
I turn the auto-update to false, but it'll still replace config file.
Maybe this has something to do with update-check.
And it doesn‘t matter. I will wait for your gold version of plugin in the future.

**Comment by sjavi4** [comment]
> ![image](https://private-user-images.githubusercontent.com/104820910/312053865-74c82b6f-75e9-4b21-8c16-b95c9016c3f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDc5MzAsIm5iZiI6MTcxMDI0NzYzMCwicGF0aCI6Ii8xMDQ4MjA5MTAvMzEyMDUzODY1LTc0YzgyYjZmLTc1ZTktNGIyMS04YzE2LWI5NWM5MDE2YzNmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxMjQ3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmZlNjk0MTE0OTc2NDMyNmFlOWQ4NjY3MTBjMDA2MDg4YzE3OWE4MTc2MGRhNDdhNjAzZGIyZTZiOTcyOTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MPO_0l365Mn30BuATtOq9tvGmOcqxyqW_v5UlKNE55I) um I have to let you notice this. The chat function doesn't work actually. Whenever I reload the server, the config file will be replaced. No matter what I do, the plugin will load the default config. I turn the auto-update to false, but it'll still replace config file. Maybe this has something to do with update-check. And it doesn‘t matter. I will wait for your release version of plugin in the future.

I can't replicate this error, is there some problems when saving the config?

**Comment by Duan-7z** [comment]
> > ![image](https://private-user-images.githubusercontent.com/104820910/312053865-74c82b6f-75e9-4b21-8c16-b95c9016c3f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyNDc5MzAsIm5iZiI6MTcxMDI0NzYzMCwicGF0aCI6Ii8xMDQ4MjA5MTAvMzEyMDUzODY1LTc0YzgyYjZmLTc1ZTktNGIyMS04YzE2LWI5NWM5MDE2YzNmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMlQxMjQ3MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmZlNjk0MTE0OTc2NDMyNmFlOWQ4NjY3MTBjMDA2MDg4YzE3OWE4MTc2MGRhNDdhNjAzZGIyZTZiOTcyOTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MPO_0l365Mn30BuATtOq9tvGmOcqxyqW_v5UlKNE55I) um I have to let you notice this. The chat function doesn't work actually. Whenever I reload the server, the config file will be replaced. No matter what I do, the plugin will load the default config. I turn the auto-update to false, but it'll still replace config file. Maybe this has something to do with update-check. And it doesn‘t matter. I will wait for your release version of plugin in the future.
> 
> I can't reproduce this error, is there some problems when saving the config?

OK... So I re install the plugin, and I managed to solve this problem.
I find that it is the way I write the string leads to the problem.
I directly copied your example string above and changed the last command. And the config file turns into this
![image](https://github.com/sjavi4/PlayerDoll/assets/104820910/ec5bad2c-31a8-4731-a871-09f9b0eadb27)
Config is successfully loaded, and my bot finally login in.

Actually, it's a basic mistake. At first, I tried to type the two '' between command. (instead of ") So plugin can't read it. Please forgive me, I really don't know much about codes. 
Anyway, I have no questions now, you could close this ISSUE, for real. Thanks for everything. =)
