### ISSUE TITLE
doll joining then leaving instantly? seems to be having a problem with whitelist bypass (paper server)

### ISSUE THREAD

**Issue by jakekj** [sjavi4/PlayerDoll#29]
26.03 22:22:20 [Server] [INFO] buhfke issued server command: /doll spawn sugfrm01
26.03 22:22:20 [Server] [INFO] [PlayerDoll] Doll Config [-sugfrm01] Saved Successfully.
26.03 22:22:20 [Server] [INFO] [PlayerDoll] Fake Client connected to Server
26.03 22:22:20 [Server] [INFO] [PlayerDoll] Client Connected
26.03 22:22:21 [Server] [INFO] [PlayerDoll] Found Connection
26.03 22:22:21 [Server] [INFO] Player is already whitelisted
26.03 22:22:21 [Server] [INFO] Disconnecting /127.0.0.1:58290: You are not whitelisted on this server!
26.03 22:22:21 [Server] [INFO] [PlayerDoll] Client Disconnected, You are not whitelisted on this server!
26.03 22:22:21 [Server] [INFO] [PlayerDoll] Client Disconnected, End of stream
26.03 22:22:21 [Disconnect] User /127.0.0.1:58290 has disconnected, reason: You are not whitelisted on this server!

Not too sure what's causing the problem and don't particularly want to remove the whitelist, please let me know :)
This is on a paper server

**Comment by jakekj** [comment]
tried adding the specific doll uuid to the whitelist but seems to delete itself when i try get the doll to connect, very strange

**Comment by sjavi4** [comment]
Would you like to use this Test version to see if the new whitelist bypass works?
https://github.com/sjavi4/PlayerDoll/releases/tag/test

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll/releases/tag/test
v1.26.1 a small patch is updated. It should fix the problem.

**Comment by jakekj** [comment]
that fixed it, thanks so much!
