### ISSUE TITLE
Unable to spawn a doll

### ISSUE THREAD

**Issue by CupOHappiness** [sjavi4/PlayerDoll#3]
Spigot and Purpur 1.20.2 
`PlayerDoll-1.6-remapped.jar` Grabbed from [here](https://modrinth.com/plugin/playerdoll/version/1.6) 
PlayerDoll is the only plugin on the server.

Created a test doll with `/doll test create`.
The .yaml file in the plugins folder seems to be fine.
Ran `/doll test spawn`
I get `Exception while running command` in chat and nothing in logging.
All the other commands seem to edit the yaml file.

**Comment by sjavi4** [comment]
It seems like you are running a wrong plugin version "1.20 - 1.20.1" instead of "1.20.2"
Try to download a match version and test again.
(https://github.com/sjavi4/PlayerDoll/releases/download/v1.6/PlayerDoll-1.6-1.20.2.zip)

**Comment by CupOHappiness** [comment]
Using the version you provided fixes the issue. I redownloaded the one from [Modrinth](https://modrinth.com/plugin/playerdoll/version/1.6) just to check if it is I that has goofed, and it is _still broken_. 

Thanks for your help <3
