### ISSUE TITLE
Can not access doll's inventory

### ISSUE THREAD

**Issue by hebd0n** [sjavi4/PlayerDoll#30]
When running /doll inv [doll] , I am unable to put items in it's inventory. It does not let me even select items in my own inventory to try and deposit into theirs. I am looking for a workaround for this as I need to have the doll use a sword on a farm and for now it only has it's fists.

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll?tab=readme-ov-file#doll-inventories

Doll's actual inventory is PlayerInventory, currently there is no method to access all slots directly. (No armor slots, offhand slot)
The /doll inv command creates a snapshot of it's full inventory with limited interactions.
The only way to give item to doll is to let the doll pick up from the ground.

I will provide a way to access the backpack and hotbar directly next update.

**Comment by hebd0n** [comment]
How do I allow them to pick items up off the ground? As that was my next option (dropping my sword for them to pick it up), and they wouldn't pick anything up off the ground.

**Comment by hebd0n** [comment]
Heyo! Thank you. I was sat trying to deposit items in their inventory through /doll inv , and I completely forgot about /invsee through essentials. I have put items in their inventory that way for now. Thank you for getting back to me so quickly on the matter. I'm glad to hear you're still actively updating this plugin (as it's great).
