### ISSUE TITLE
Doll's attack won't provoke zombified piglin/pigmen

### ISSUE THREAD

**Issue by HeroDiamonds428** [sjavi4/PlayerDoll#31]
https://github.com/sjavi4/PlayerDoll/assets/51848907/b0d42cc7-c2cb-4697-a1de-6d50487896b8

**Comment by sjavi4** [comment]
Did you turn on the invincible / hostility?

**Comment by HeroDiamonds428** [comment]
It seems like the invincibility was on.
after toggling the setting on and off, the pigmen started getting angry at the doll.
thank you.
