### ISSUE TITLE
cant change prefix

### ISSUE THREAD

**Issue by Potenza7** [sjavi4/PlayerDoll#33]
I want to remove the - prefix in the doll. I want to do something else or destroy it completely, but I cannot do this from the prefix settings. Can you fix this or add such a feature?

**Comment by sjavi4** [comment]
This prefix can be removed, but it will confuse the command system and players.
Since some commands are executed base on player name.
Doll prefix will add as a config setting if there is no technical problems

**Comment by ditt0132** [comment]
is this config option added?
and how to remove it now?
i tried remove it on doll yml and removed it from filename, yml but cannot spawn it with new name, old name too

**Comment by sjavi4** [comment]
Configurable prefix will be added in next update.
There are still few more problems need to be fixed.

**Comment by sjavi4** [comment]
https://modrinth.com/plugin/playerdoll/version/1.33 has released.
