### ISSUE TITLE
right click cannot open gui

### ISSUE THREAD

**Issue by milu2048** [sjavi4/PlayerDoll#36]
When I right-click doll and I get "Unknown command. Type '/help' for help." I suspect it's a permission problem, so I give the permission with luckperms, but I get the same error

**Comment by sjavi4** [comment]
it is a problem when using BungeeCord mode.

I don't know why using BungeeCord would fail to call command when player is sending command which not typed in chat.

During my test in v1.28.1, only purpur 1.20.6 could execute the command in BungeeCord mode.

**Comment by sjavi4** [comment]
version 1.29 has released to fix this bug. Also a patch for BungeeCord connection.

https://modrinth.com/plugin/playerdoll/version/PYo9gdCJ
