### ISSUE TITLE
Doll attack problem

### ISSUE THREAD

**Issue by shallmeow** [sjavi4/PlayerDoll#37]
Doll can't attack without target.
Anything I can do? 
Cause some farm need to attack Armor Stand.
Thanks a lot.

**Comment by sjavi4** [comment]
Are you placing Doll at spawn protection area?

Doll should always be attacking if it is at interval mode, despite Doll do not play the swing arm animation if no valid entity or block

Continuous mode is for block breaking

**Comment by shallmeow** [comment]
Oh I got it.
It's working.
Thanks again!
