### ISSUE TITLE
Permission may not working well

### ISSUE THREAD

**Issue by 1264175987** [sjavi4/PlayerDoll#39]
I use LuckPerms for permission.
plugin version is 1.29 (also tried 1.28), folia version is 1.20.4.
the player who have the permission 'playerdoll.perm.max-doll-create.a' can not create even one BOT.
the player have 'playerdoll.perm.max-doll-create.b' can create only one BOT.
the player have 'playerdoll.perm.max-doll-create.c' can create tow BOT.
If an operator remove the player's bot, He will not be able to create a new one again (It looks cumulative).

If it's a problem with my settings, please tell me, sorry to bother you.

This is my perm.yml:
[perm.txt](https://github.com/user-attachments/files/15944871/perm.txt)

**Comment by sjavi4** [comment]
It seems like I didn't make the counter decrease when remove, the creation counter should reset after server restart.

I will check the code, if any problems were found, an update patch will release soon.

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll/commit/0246ab235babba888c5dd86b3350068509a31222

Fixed [v1.29.1](https://modrinth.com/plugin/playerdoll/version/1.29)
