### ISSUE TITLE
perm issue

### ISSUE THREAD

**Issue by 1264175987** [sjavi4/PlayerDoll#41]
I set a  "max-doll-create" group in perm.yml, and give players permission "max-doll-create.A".
But they can not create doll ,they will be reminded that they have reached the creation limit.

Here is the perm.yml:
[perm.txt](https://github.com/user-attachments/files/16014917/perm.txt)

**Comment by sjavi4** [comment]
The full permission is "playerdoll.perm.max-doll-create.[Your Group]"
ie LuckPerms usage `/lp user [User] permission set playerdoll.perm.max-doll-create.A true`

**Comment by 1264175987** [comment]
The permission I gave to the player was right
![image](https://github.com/sjavi4/PlayerDoll/assets/81815625/cb0435eb-314e-4608-8166-b08c14ed627b)

**Comment by sjavi4** [comment]
Did they create doll before?

**Comment by 1264175987** [comment]
No ,I deliberately found a player who had never tried it before

**Comment by sjavi4** [comment]
there is a comparison mistake from Create command.
Will fix in next version

**Comment by sjavi4** [comment]
https://modrinth.com/plugin/playerdoll/version/o8qhqPRd
Fixed https://github.com/sjavi4/PlayerDoll/commit/ba6d099c6c1b170675e5db80dbb7ad13c91bb9a9
