### ISSUE TITLE
despawn or tp issues

### ISSUE THREAD

**Issue by 1264175987** [sjavi4/PlayerDoll#44]
Use '/doll tp' and then '/doll despawn' ,server will crash.
[log.txt](https://github.com/user-attachments/files/16018111/log.txt)

**Comment by sjavi4** [comment]
https://modrinth.com/plugin/playerdoll/version/o8qhqPRd
Fixed https://github.com/sjavi4/PlayerDoll/commit/ba6d099c6c1b170675e5db80dbb7ad13c91bb9a9
