### ISSUE TITLE
Server crashed when player kill a BOT

### ISSUE THREAD

**Issue by 1264175987** [sjavi4/PlayerDoll#46]
A player kill a doll when there is many other players beside himself.

here is the log
[log.txt](https://github.com/user-attachments/files/16030861/log.txt)

**Comment by sjavi4** [comment]
cannot be reproduced together with #44.
Is there any BungeeCord, plugins or settings that make this happen.
I didn't encounter these bugs using default Luminol. (bungeecord disabled)

**Comment by sjavi4** [comment]
If you have no specific usage on these command. 
As a temporary solution, you can force set Doll to be invulnerable and disable TP for everyone.
