### ISSUE TITLE
[Bug] Logic error in max-doll-create causing actual limit less than configured value

### ISSUE THREAD

**Issue by shou692199** [sjavi4/PlayerDoll#47]
I set `max-doll-create` in default group to 5, but I can only create 4 dolls. So I dug into the code and found out:
In `DollManager.java` at line 166
`exceed = currentCount >= maxCreationMap.get(group);`
should be modify to
`exceed = currentCount > maxCreationMap.get(group);`
in order to fix it.

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll/commit/ba6d099c6c1b170675e5db80dbb7ad13c91bb9a9
