### ISSUE TITLE
The doll died for unknown reasons

### ISSUE THREAD

**Issue by 1264175987** [sjavi4/PlayerDoll#49]
**Describe the bug**
The doll died for unknown reasons.

 - 1.20.4
 - 1.29.1
 - luminol-1.20.4-bundler   d753f16
 - Velocity

**To Reproduce**
1. OP create a doll
2. OP give this doll by edit this doll's config file
3. Player spawn the doll

**Screenshots or Videos**
If applicable, add screenshots or videos to help explain your problem.
![1](https://github.com/sjavi4/PlayerDoll/assets/81815625/f83e4cc8-b353-4b3a-bc5f-15e416f53e13)

**Context in code (If applicable)**

**Comment by sjavi4** [comment]
It seems the Doll was killed by the sync plugin, setting the Doll to 0 HP.
Seemingly like the Doll was died before and saved by the plugin.

**Comment by sjavi4** [comment]
Does version 1.29.1 with Latest Luminol solve the crash problem?

**Comment by 1264175987** [comment]
no, i posted a new issues

**Comment by zhjc2021** [comment]
this bug also happen with PlayerDoll version 1.30
1.30 isn't fix this bug

**Comment by sjavi4** [comment]
> this bug also happen with PlayerDoll version 1.30 1.30 isn't fix this bug

I mean the crash problem. The HP sync issue is working on progress

**Comment by sjavi4** [comment]
https://modrinth.com/plugin/playerdoll/version/qbQF1ESr

Here is the bug fix, please let me know if the problem didn't solve.

https://github.com/sjavi4/PlayerDoll/commit/2977e745064b37b63b245920ef629d6bf8642849
https://github.com/sjavi4/PlayerDoll/commit/1af2ad27bcb1f13fc2ddcb8f8d6803748994253c

**Comment by zhjc2021** [comment]
i will test this version tonight.
