### ISSUE TITLE
The doll becomes invincible after going from 'the end' to 'overworld'

### ISSUE THREAD

**Issue by 1264175987** [sjavi4/PlayerDoll#50]
**Describe the bug**
The doll becomes invincible after going from 'the end' to 'overworld'

 - 1.20.4
 - 130.1

**To Reproduce**
1. push doll in to the portal
2. doll teleport to overworld
3. doll becomes invincible can't get damage

**Expected behavior**
doll can be kill by command ‘/kill’
Issues will not happen when doll teleport from overworld to the end

**Comment by sjavi4** [comment]
Seems like something interferes with the End Credit.

**Comment by sjavi4** [comment]
https://modrinth.com/plugin/playerdoll/version/CV8YgCKe

https://github.com/sjavi4/PlayerDoll/commit/f1d302b0dfe283ce9d07b0c1020f82772f34ca34
https://github.com/sjavi4/PlayerDoll/commit/6a44ee9120e0c83db66719fe73434f540d5b8317

**Comment by sjavi4** [comment]
Also there is an crash fix for Folia about action ticking. Don't know will this be helpful with your crashing issue.
