### ISSUE TITLE
Players can not change skin

### ISSUE THREAD

**Issue by 1264175987** [sjavi4/PlayerDoll#51]
**Describe the bug**

 - 1.20.4
 - 1.30.1

**To Reproduce**
Player can only use command /create [dollname]
It looks like they don't have permission when using /create [dollname] [dollskin]

**Comment by zhjc2021** [comment]
player without op permission can only use /doll create [dollname]
they cannot use /doll create [dollname] [skinName]

**Comment by sjavi4** [comment]
There is an permission for skin setting in Create `playerdoll.argument.create.skin`
Would it solve the problem?

**Comment by zhjc2021** [comment]
yes it solve the problem
