### ISSUE TITLE
can't use the chat-when-join part

### ISSUE THREAD

**Issue by achenrhyc** [sjavi4/PlayerDoll#52]
**Describe the bug**

 - Minecraft Version 1.21
 - Plugin Version spigot-1.21

Test environment: No additional plug-ins are installed

**To Reproduce**
Modify the chat-when-join section of the configuration file

For example, change it to:
chat-when-join:
- 'msg'
After restarting the server, you will find that the plugin automatically removes the quotation marks and cannot be used
It's going to look like this
- msg

If modified to:
chat-when-join:
- '123'
The plug-in does not remove the quotation marks after restarting the server, but it is still unavailable

**Expected behavior**

**Comment by sjavi4** [comment]
Fixed, v1.30.3
https://modrinth.com/plugin/playerdoll/version/IeHuNZ8Y

https://github.com/sjavi4/PlayerDoll/commit/bd4d6ff5f325ed2e058d9cd6472c13693c7c706c
