### ISSUE TITLE
Cpu usage increased 100%

### ISSUE THREAD

**Issue by SavageTheUnicorn** [sjavi4/PlayerDoll#55]
This plugin is COOL, but increases idle cpu usage from ~30% to ~130% (my server goes up to 400%). Latest plugin version, purpur 1.20.4, running on a 4core(one thread per core) system with 24gb ram. No dolls were spawned or loaded in any world. Definitely not viable on a server with player counts higher than 10 unless you have JUICED hardware.
Oracle Cloud Ampere A1 instance btw.

**Comment by sjavi4** [comment]
can you provide a spark profile?

**Comment by sjavi4** [comment]
It seems like the config `convert-player` is using 1 of the threads at maximum rate.

Did you turn this option to true?

**Comment by SavageTheUnicorn** [comment]
I did, in the config it said it was required to use some commands.

**Comment by sjavi4** [comment]
if you want to use some action commands to control real players, then turn this on. Or else the option has no use.

**Comment by SavageTheUnicorn** [comment]
Ahhh thanks for the clarification! I actually have a seperate plugin for controlling players and one for running cmds as them so this feature is lost on me for sure. I'll test with this option disabled!

**Comment by sjavi4** [comment]
A new version is released for the CPU usage issue

https://modrinth.com/plugin/playerdoll/version/1.32

https://github.com/sjavi4/PlayerDoll/commit/d0bf5681d95c2eeeb929bd426f2cef5aae58b52f
https://github.com/sjavi4/PlayerDoll/commit/b7ca6c75f8f84070d63f95892325dfaaf93e0c9a
