### ISSUE TITLE
Cannot invoke "String.equals(Object)" because "me.autobot.playerdoll.PlayerDoll.INTERNAL_VERSION" is null

### ISSUE THREAD

**Issue by hkkongou** [sjavi4/PlayerDoll#58]
**Describe the bug**
cannot use any command of the plugin

 - 1.20.1
 - Plugin Version
 - purpur-1.20.1-2060
 - flamecord
 - https://paste.denizenscript.com/View/124630

**To Reproduce**
1. install the plugin
2. command cannot use

**Expected behavior**
command can use

**Setting of Doll**
haven't use any doll

**Screenshots or Videos**
no

**Context in code (If applicable)**
no

**Additional context**
no

**Comment by sjavi4** [comment]
1.20.1 is not supported in newer version after PlayerDoll v1.24.1.
You may upgrade your server to 1.20.4+ to use the latest plugin, or use PlayerDoll v1.24.1.

Be aware, old versions are out of support.
