### ISSUE TITLE
"-Chunk doesn't have data pre-loaded, they have never been processed during pre-login in this session. - denying login."

### ISSUE THREAD

**Issue by leothawne** [sjavi4/PlayerDoll#60]
![image](https://github.com/user-attachments/assets/fd43521d-7d52-40fe-b426-5dbc7eceb32e)
[latest.log](https://github.com/user-attachments/files/16261914/latest.log)

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll/issues/54

Should be the same solution.

**Comment by leothawne** [comment]
Thanks!
