### ISSUE TITLE
doll won't rejoin

### ISSUE THREAD

**Issue by pidan8** [sjavi4/PlayerDoll#62]
the doll won't rejoin after I set Join at server start

**Comment by sjavi4** [comment]
If you are using BungeeCord. Doll can only be joined after a real player has connected.

**Comment by pidan8** [comment]
i am running purpurmc so cant auto rejoin?

**Comment by pidan8** [comment]
> If you are using BungeeCord. Doll can only be joined after a real player has connected.

i am running purpurmc so cant auto rejoin?

**Comment by sjavi4** [comment]
https://modrinth.com/plugin/playerdoll/version/1.33

Should Fix
