### ISSUE TITLE
In GroupManager, wildcard does't work

### ISSUE THREAD

**Issue by chinese-wzq** [sjavi4/PlayerDoll#65]
I use `playerdoll.command.*` in my GroupManager config file `groups.yml`, but player still doesn't have the permission to execute `/doll create`, but if I directly write `playerdoll.command.create`, it works!

In the first case, if I execute `/manucheckp playername playerdoll.command.create` in console, it says `SuperPerms report node: false`. But in the second case, the output is `SuperPerms report node: true`. In my understanding, 'playerdoll.command.*' should be equal to 'playerdoll.command.create'.

**Comment by sjavi4** [comment]
After looking the examples.
[Essentials's permission config](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/resources/plugin.yml).
Maybe the wildcard node must be manually added in plugin.yml.

PlayerDoll doesn't provide such wildcard node, which is similar to [Residence's permission config](https://github.com/Zrips/Residence/blob/master/src/plugin.yml). Can you use wildcard for Residence permissions?

**Comment by chinese-wzq** [comment]
I have no idea...Maybe it's impossiable. I belive PlayerDoll should use the way of Essentials, which is convinent in most cases.

**Comment by sjavi4** [comment]
You can ask AI to generate a list for you.

**Comment by sjavi4** [comment]
https://modrinth.com/plugin/playerdoll/version/1.34
