### ISSUE TITLE
After I updated the plug-in version, the updated plug-in could not read the previous doll information

### ISSUE THREAD

**Issue by milu2048** [sjavi4/PlayerDoll#67]
**Describe the bug**
After I updated the plug-in version, the updated plug-in could not read the previous doll information

 - Folia 1.20.6
 - playdoll 1.32 -> playdoll 1.33.1
 - no Proxy

**To Reproduce**
1. use /doll speaw
4. See error No previous doll data

**Expected behavior**

**Setting of Doll**
No change

**Screenshots or Videos**
![image](https://github.com/user-attachments/assets/044ea95d-651c-4ee3-8ef0-16ca8f17132c)
Ceng5 is new doll , I also have Ceng1 Ceng2 Ceng3

**Related Setup (If your problem is related to 3rd parties)**
No change

**Context in code (If applicable)**

**Additional context**

**Comment by sjavi4** [comment]
v1.33 uses is not compatible to old doll configs.


A upgrade flow has documented in Modrinth

**Comment by milu2048** [comment]
Ok, thanks for your comments
