### ISSUE TITLE
When repeatedly click to preview the backpack item, the item will disappear.

### ISSUE THREAD

**Issue by minrog666** [sjavi4/PlayerDoll#72]
**Describe the bug**

 - Minecraft Version - 1.21
 - Plugin Version - 1.33
 - Server Jar name and version - PurPur 2276 1.21

**To Reproduce**
1. Create and spawn a doll
2. put item to doll backpack
3. use command /doll inv <dollname>
4. use Shift + Repeat left-click doll backpack items  

**Screenshots or Videos**
video file size too big so use google drive
[https://drive.google.com/file/d/127BgjOolv_ZIXHkVO3_gWj1l1zOXpD1V/view?usp=sharing](https://drive.google.com/file/d/127BgjOolv_ZIXHkVO3_gWj1l1zOXpD1V/view?usp=sharing)

**Comment by sjavi4** [comment]
Should be fixed next version

**Comment by sjavi4** [comment]
https://modrinth.com/plugin/playerdoll/version/1.34
