### ISSUE TITLE
Null point exception when server start

### ISSUE THREAD

**Issue by LoliWolf** [sjavi4/PlayerDoll#74]
Errror occurred while enabling PlayerDoll v1.28 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.autobot.playerdoll.PlayerDoll$ServerBranch.setupScheduler(org.bukkit.plugin.Plugin)" because "me.autobot.playerdoll.PlayerDoll.serverBranch" is null

spigot 1.21
using plugin:
cmilib
cmi

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll/wiki/Configs#basic-config

If the server cannot detect server, you can assign it in config -> server-mod

Or, you can try update your plugin
