### ISSUE TITLE
Doll failed to spawn Not enough bytes in buffer

### ISSUE THREAD

**Issue by cgw2023** [sjavi4/PlayerDoll#76]
**Describe the bug**
I cannot spawn doll 

 - Minecraft Version: 1.20.4 vanilla
 - Plugin Version : PlayerDoll-1.34
 - Server Jar name and version: folia 1.20.4
 - Proxy name in use: velocity
 - Server Log: https://paste.denizenscript.com/View/125298

**To Reproduce**
1. /doll create hellooworld
2. /doll spawn
3. error occur

**Expected behavior**
doll can spawn

**Server Setting**
velocity online mode
installed plugin on folia server

**Setting of Doll**
default setting (new generated)

**Screenshots or Videos**

**Related Setup (If your problem is related to 3rd parties)**
- No

**Context in code (If applicable)**

**Additional context**

**Comment by sjavi4** [comment]
![image](https://github.com/user-attachments/assets/3050da4c-0c48-43d9-8c9e-665fb248ab99)

Tested.
- Windows
- latest Velocity (modern forward mode)
- Folia 1.20.4
- PlayerDoll v1.34


Should be fine with spawning, 
Do you have any software which is out of date?

**Comment by cgw2023** [comment]
i don't have any other plugin in velocity or in folia server
![image](https://github.com/user-attachments/assets/2bf4fa4b-2c4e-462d-b21d-16a98089e068)

plugin setting https://paste.denizenscript.com/View/125301
velocity setting https://paste.denizenscript.com/View/125302

is there anything wrong here?

**Comment by sjavi4** [comment]
How about the version of Folia server.
Would it make a difference?

**Comment by cgw2023** [comment]
I am using the last version of 1.20.4 which is ec6b172

**Comment by cgw2023** [comment]
I got the same problem when I am using purpur-1.20.2-2091 behind velocity
`lost connection: Internal Exception: io.netty.handler.codec.DecoderException: Not enough bytes in buffer, expected 3, but got 0`

So it seems like not a folia problem.

**Comment by cgw2023** [comment]
Do you have a recommended velocity->folia/pupur(paper) configuration steps can give me so that I can double check whether my installation and configurations are correct?

**Comment by cgw2023** [comment]
> Velocity config https://paste.denizenscript.com/View/125320 Folia paper config https://paste.denizenscript.com/View/125321 Server properties https://paste.denizenscript.com/View/125322

I figured out that `network-compression-threshold=-1` in server.properties of folia is the cause of this problem, -1 is recommended by the community since the compression will be handled by the velocity instead, will it be possible for you to add support for -1 network compress threshold setting(which means no compression is performed)?

**Comment by sjavi4** [comment]
https://modrinth.com/plugin/playerdoll/version/1.35

After some tests, the connection should work fine in this version.

**Comment by cgw2023** [comment]
> https://modrinth.com/plugin/playerdoll/version/1.35Dev
> 
> After some tests, the connection should work fine in this version.

i got an error when i spawn the npc and the folia server will crash
https://paste.denizenscript.com/View/125548

**Comment by sjavi4** [comment]
> i got an error when i spawn the npc and the folia server will crash https://paste.denizenscript.com/View/125548

Anything make the npc become that far away?
Does re-create a new one still causing the crash?

**Comment by cgw2023** [comment]
> > i got an error when i spawn the npc and the folia server will crash https://paste.denizenscript.com/View/125548
> 
> Anything makes the npc become that far away? Does re-create a new one still causing the crash?

The npc should have been log off in that location previously.  Which caused this problem.

In version 1.36, i can see that when the npc spawn, the npc will be teleport to the command issued player, i think this problem should have been solved some  how.

I will try to install this in production server and see if there is any problem, thx
