### ISSUE TITLE
Permissions don't work

### ISSUE THREAD

**Issue by Hzcrow** [sjavi4/PlayerDoll#78]
I created a new permission group,but when i tried to set permissions of this plugin,they did not work at all.
I first tried to set 'playerdoll.doll',but it did not work.When i remove my op permission,I can't use any commands
This means the rdinary players can't use the plugin.
Then I set all of the permissioms from the plugin. Unluckily,it still not work.
The console has no errors
![2024-08-12_13 40 50](https://github.com/user-attachments/assets/28a31bcc-3bf2-4fde-9c64-f74d88c05e72)
![2024-08-12_13 42 20](https://github.com/user-attachments/assets/9211ab35-646f-4eca-8569-9409741d49b2)
And here's the picture when i set myself op and use the commands.
![2024-08-12_13 42 35](https://github.com/user-attachments/assets/dd86b16c-9a56-47d0-85b4-c502576fe461)

The server parameters are as follows
paper-1.21-124
PlayerDoll-1.35
permission plugin:LuckPerms-Bukkit-5.4.137

**Comment by sjavi4** [comment]
https://github.com/sjavi4/PlayerDoll/wiki/Commands-&-Permissions#note

Commands permissions are under the following format "playerdoll.command.<subcommands>"



if you want to set a wildcard for commands you can have a look to this.

https://github.com/sjavi4/PlayerDoll/wiki/Commands-&-Permissions#wildcards

**Comment by Hzcrow** [comment]
Thanks.It works
