### ISSUE TITLE
Does doll count as player ? 

### ISSUE THREAD

**Issue by vxkShelby** [sjavi4/PlayerDoll#8]
btw - add rename function ... 

It show in TAB list but it dont show on hosting that he is joined (i mean its showing 0/100 players) ... is it possible to make or should i look for another plugin ?

**Comment by vxkShelby** [comment]
On hosting its says 0/100 but on other formats it says right number

**Comment by sjavi4** [comment]
Rename function will be added on next patch.
Doll works very close to real player.
If you want to modify the list, you should look for other plugins to support it, since it require NMS. 
(maybe i will add this some day.)
