### ISSUE TITLE
1.21.1 Unable to summon PlayerDoll properly

### ISSUE THREAD

**Issue by CaesarGalahad** [sjavi4/PlayerDoll#80]
After executing the '/playerdoll spawn ID' command in version 1.21.1, PlayerDoll did not spawn and nothing happened

Server INFO
Server version ：PurPur 2287 1.21.1
PlayerDoll Version 1.35.2

Server LOG
https://mclo.gs/JchcQWU

**Comment by sjavi4** [comment]
Should fix

https://modrinth.com/plugin/playerdoll/version/9l9UrXu7

**Comment by CaesarGalahad** [comment]
There still seems to be some issues with 1.35.3

LOG
https://mclo.gs/XTGe4hs

**Comment by sjavi4** [comment]
A new Doll connection is trying to connect to a closed EventLoopGroup.
Try to restart the server?

**Comment by CaesarGalahad** [comment]
This issue is solved, thank you

**Comment by CaesarGalahad** [comment]
There still seems to be some issues with 1.35.3
LOG
https://mclo.gs/1BCtCHD

**Comment by sjavi4** [comment]
The plugin is currently not support /reload command, and it is not encouraged to do so.
I will try to implement reload logics in the future.

**Comment by CaesarGalahad** [comment]
I didn't use the reload command, I restarted the server and the plugin loaded successfully, but when I executed the /spawn command, it would give an error

LOG
https://mclo.gs/1BCtCHD

**Comment by CaesarGalahad** [comment]
I provide you with a complete server log so that you can analyze the problem

FULL LOG
https://mclo.gs/y10j3E3

**Comment by sjavi4** [comment]
Sorry for misunderstanding, there is like 50% chance that the JVM find the method of the class wrongly in every startup.
Should fix this time.
https://modrinth.com/plugin/playerdoll/version/HsyvWNAa

**Comment by CaesarGalahad** [comment]
Now all the problems are solved, thank you very much for your help
PlayerDoll can now run on 1.21.1
