### ISSUE TITLE
Add console support

### ISSUE THREAD

**Issue by githubuser2304** [sjavi4/PlayerDoll#82]
**Describe the bug**
Console commands or command blocks are not supported in any way.

 - Minecraft Version: 1.21
 - Plugin Version: v1.35.4

**To Reproduce**
1. Create and spawn a new doll
2. Try to automatically start some doll actions (e.g. "/doll use testuser once" via command block).

Even workarounds like "execute as testuser at @s run doll use testuser once" (via command block) are detected as non-player commands.

**Additional context**
To add some background information to this issue: I want to setup a little city run by FakePlayers. If a real player enters the city and triggers a pressure plate, the FakePlayers should start working. I want to "start" their jobs via command blocks triggered by the real player. I am also open for other solutions/workarounds to automatically "start" FakePlayers after they join.

**Comment by sjavi4** [comment]
Next update

**Comment by sjavi4** [comment]
An update has released.
https://modrinth.com/plugin/playerdoll/version/1.36
