### ISSUE TITLE
GUI translation for bot

### ISSUE THREAD

**Issue by JacksonsY** [sjavi4/PlayerDoll#83]
<img width="710" alt="20240816231933" src="https://github.com/user-attachments/assets/d9450d89-844b-4788-b8e3-ae6fb8e3b80e">
I need to translate the GUI of the bot. Where can I set it up

**Comment by sjavi4** [comment]
You can setup your own translation in plugins/PlayerDoll/language/\<name\>.yml
Once you finished setup the language config, you need to change the loading language in config.yml -> language: \<name\>

The default language (english)
https://github.com/sjavi4/PlayerDoll/blob/latest/PlayerDoll-Common/src/main/resources/default.yml

Tranditional Chinese
https://github.com/sjavi4/PlayerDoll/blob/main/customlanguages/zh.yml

It is welcome to provide your translated config for the public.
