### ISSUE TITLE
Set Doll to constantly look at something

### ISSUE THREAD

**Issue by Pixle36** [sjavi4/PlayerDoll#9]
Setting the ability for a doll to lock onto a target would be super useful in the case of a doll riding in a minecart and needing to put coal in a furnace minecart in front it

**Comment by sjavi4** [comment]
This might reqiure a new system to make this possible. (ie mob AI / more advanced doll action system)
Can be developed, but not that prior.

**Comment by sjavi4** [comment]
See v1.16 changelog in Modrinth (https://modrinth.com/plugin/playerdoll/version/1.16)
The lookat command update should fulfill your needs
