### ISSUE TITLE
Removing a Doll with the same name as an online player kills the player

### ISSUE THREAD

**Issue by seeruk** [sjavi4/PlayerDoll#94]
**Describe the bug**
Since Dolls can have any name, and they are created separately to them being spawned, it's possible to create a Doll with the same name as a player. If the player is online, PlayerDoll considers that player as that Doll having been spawned, it seems. If a player has created a Doll with the same name as an actual player, and that player is online, and the Doll creator then decides to remove the doll (via `/doll remove <player>`), the actual player is killed.

The actual player can be killed without having any sort of elevated permissions (e.g. not opped, only having `playerdoll` permission nodes and/or other nodes for regular survival player-level gameplay).

 - Minecraft Version: 1.21.1
 - Plugin Version: 1.36
 - Server Jar name and version: Purpur 1.21.1-2308-ver/1.21.1@8332fa4
 - Proxy name in use: Velocity v3.3.0-SNAPSHOT
 - Server Log:

**To Reproduce**
1. Log into a server with PlayerDoll enabled
2. Create a doll with an online player's name, you can even use your own player name if you like
3. While that player is online (even yourself), remove the Doll via `/doll remove`
4. Observe that the actual player is killed

Here's a screenshot of it in action, with the server console showing the commands used: https://imgur.com/a/nxitHIs

As you can see from the screenshot, I already had a Doll (called SeerUKBot), which I then removed to create the SeerUK bot. I tried to spawn it, but it said the Doll is already spawned. I tried to despawn it, and it said it couldn't find the target. Then I removed the Doll, and immediately died.

**Expected behavior**
It should not be possible to kill real players.

**Server Setting**
State if you changed some uncommon settings
i.e. Whitelist, Online-mode, specific server-mod settings

**Setting of Doll**
Doll's current setting. From config or GUI. This might be helpful when clarifing the problem
i.e. Hostility = true / Gravity: false

**Screenshots or Videos**
https://imgur.com/a/nxitHIs

**Related Setup (If your problem is related to 3rd parties)**
- Resource Packs
- Server Properties
- Others

**Context in code (If applicable)**

**Additional context**

**Comment by sjavi4** [comment]
Confirmed. Will be fixed in next release

**Comment by sjavi4** [comment]
https://modrinth.com/plugin/playerdoll/version/1.37

Tested and should fixed.
https://github.com/sjavi4/PlayerDoll/commit/5aaa56372605001d861caed27daf5a0e7f5149e8#diff-c29b9ce042ffb270c05b0a9acb1caa19a7ab50effc7e5478463e607ec8c8fc68
https://github.com/sjavi4/PlayerDoll/commit/5aaa56372605001d861caed27daf5a0e7f5149e8#diff-832b5050269d42344de67a646d7c1131614a4ef9a789a9f9335811e7a3f75da7

**Comment by seeruk** [comment]
Thanks for the swift turnaround on this, can confirm that that's resolved now. Much appreciated!
